name: open-issue-with-yml-text
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "This should execute!!"
        run: 'ls -a'
