name: open-issue-with-yml-text
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Retrieve deployment configuration"
        id: deploy
        run: echo DEPLOY=$(cat deploy.yml | yq '.environments[] | select(.name == "preint") | .countries | unique | join(",")')
